### ISSUE TITLE
DEBUG log messages repeat inside later log messages

### ISSUE THREAD

**Issue by AminArria** [erlang-ls/erlang_ls#1157] opened 2021-12-16 08:35 UTC
**Describe the bug**
I set logging to `DEBUG` and the generated log for `[SERVER] Sending notification` are including previous logs which makes the log grow REALLY fast in size, in a couple minutes it generated ~100MB.

This is an example of how just 1 log message grows in size, scroll horizontally or search for `Sending notification [notification=Content-Length: 178` which is part of the first log message

```
[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>

[2021-12-16T08:35:41.318844+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 438, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {\"jsonrpc\":\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\\n\",\"type\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>

[2021-12-16T08:35:41.324386+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 732, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.318844+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 438, , {\"jsonrpc\":\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"window/logMessage\\\",\\\"params\\\":{\\\"message\\\":\\\"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\\\\n\\\",\\\"type\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\n\",\"type\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>

[2021-12-16T08:35:41.613027+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1094, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.324386+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 732, , {\"jsonrpc\":\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"[2021-12-16T08:35:41.318844+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 438, , {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"window/logMessage\\\",\\\"params\\\":{\\\"message\\\":\\\"[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"method\\\\\\\":\\\\\\\"window/logMessage\\\\\\\",\\\\\\\"params\\\\\\\":{\\\\\\\"message\\\\\\\":\\\\\\\"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\\\\\\\\n\\\\\\\",\\\\\\\"type\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\n\\\",\\\"type\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\n\",\"type\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>

[2021-12-16T08:35:41.780175+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1593, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.613027+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1094, , {\"jsonrpc\":\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"[2021-12-16T08:35:41.324386+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 732, , {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"window/logMessage\\\",\\\"params\\\":{\\\"message\\\":\\\"[2021-12-16T08:35:41.318844+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 438, , {\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"method\\\\\\\":\\\\\\\"window/logMessage\\\\\\\",\\\\\\\"params\\\\\\\":{\\\\\\\"message\\\\\\\":\\\\\\\"[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {\\\\\\\\\\\\\\\"jsonrpc\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"2.0\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"method\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"window/logMessage\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"params\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\\\\\n\\\\\\\",\\\\\\\"type\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\n\\\",\\\"type\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\n\",\"type\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>

[2021-12-16T08:35:41.960030+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 2364, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.780175+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1593, , {\"jsonrpc\":\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"[2021-12-16T08:35:41.613027+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1094, , {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"window/logMessage\\\",\\\"params\\\":{\\\"message\\\":\\\"[2021-12-16T08:35:41.324386+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 732, , {\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"method\\\\\\\":\\\\\\\"window/logMessage\\\\\\\",\\\\\\\"params\\\\\\\":{\\\\\\\"message\\\\\\\":\\\\\\\"[2021-12-16T08:35:41.318844+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 438, , {\\\\\\\\\\\\\\\"jsonrpc\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"2.0\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"method\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"window/logMessage\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"params\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"jsonrpc\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"2.0\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"method\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"window/logMessage\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"params\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\\\\\n\\\\\\\",\\\\\\\"type\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\n\\\",\\\"type\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\n\",\"type\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>

[2021-12-16T08:35:42.170763+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 3679, , {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-12-16T08:35:41.960030+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 2364, , {\"jsonrpc\":\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"[2021-12-16T08:35:41.780175+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1593, , {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"window/logMessage\\\",\\\"params\\\":{\\\"message\\\":\\\"[2021-12-16T08:35:41.613027+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 1094, , {\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"method\\\\\\\":\\\\\\\"window/logMessage\\\\\\\",\\\\\\\"params\\\\\\\":{\\\\\\\"message\\\\\\\":\\\\\\\"[2021-12-16T08:35:41.324386+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 732, , {\\\\\\\\\\\\\\\"jsonrpc\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"2.0\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"method\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"window/logMessage\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"params\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"[2021-12-16T08:35:41.318844+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 438, , {\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"jsonrpc\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"2.0\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"method\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"window/logMessage\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"params\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[2021-12-16T08:35:41.160584+01:00] [debug] [SERVER] Sending notification [notification=Content-Length: 178, , {\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"jsonrpc\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"2.0\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"method\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"window/logMessage\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"params\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"message\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[2021-12-16T08:35:41.143711+01:00] [info] Started erlang_ls server [erlang_ls:main/1 L29] <0.9.0>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\\\\\n\\\\\\\",\\\\\\\"type\\\\\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\\\n\\\",\\\"type\\\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\\n\",\"type\":4}}] [els_server:do_send_notification/3 L202] <0.166.0>\n","type":4}}] [els_server:do_send_notification/3 L202] <0.166.0>
```

**To Reproduce**
1. Set log level to `DEBUG`
2. Use erlang_ls (in my case I use VS Code extension)
3. See logs exploding in size

**Expected behavior**
Logs don't include previous logs in them

**Context**
 - `erlang_ls` version (tag/sha): `0.21.2` with OTP 24
 - Editor used: VS Code with extension version `v0.0.32`

**Comment by robertoaloi** [comment] 2021-12-16 08:38
Hi @AminArria and thanks for the report. This is a known issue. Closing as a duplicate of https://github.com/erlang-ls/erlang_ls/issues/1050

**Closed by robertoaloi** 2021-12-16 08:38 UTC
Labels: bug
