### ISSUE TITLE
After a while erlang-ls send errors to output

### ISSUE THREAD

**Issue by Taure** [erlang-ls/erlang_ls#688] opened 2020-04-27 11:31 UTC
**Describe the bug**
It feels like something happen with the erlang-ls node and suddenly it generate errors like:
`[Error - 1:20:19 PM] Request textDocument/codeAction failed.
  Message: Unexpected error while textDocument/codeAction
  Code: -32001 

[Error - 1:20:20 PM] Request textDocument/hover failed.
  Message: Unexpected error while textDocument/hover
  Code: -32001 

[Error - 1:20:20 PM] Request textDocument/hover failed.
  Message: Unexpected error while textDocument/hover
  Code: -32001 `

**To Reproduce**
Hard to reproduce. Not sure what trigger this yet.

**Expected behavior**
Request to erlang-ls should not fail

**Actual behavior**
after a while it starts failing with request against erlang-ls and it sends much errors to output tab and send notification in the editor.

**Context**
 - `erlang_ls` version (tag/sha): 0.3.0
 - Editor used: visual studio code
 - Environment: Windows 10 with WSL running ubuntu
 - LSP client used:

**Comment by robertoaloi** [comment] 2020-04-27 11:35
What I suspect is that something is sending output to stdio. Since the VS Code extension is using stdio as a transport, messages cannot be parsed correctly since they are mixed with other stuff. We should find a way to reproduce this. Do the server logs show anything interesting?

**Comment by alanz** [comment] 2020-04-28 13:23
I wonder if this is also #671?

**Comment by robertoaloi** [comment] 2020-04-28 15:33
@Taure Can you let us have the server logs? They should contain the actual error. Something like "Unexpected error [type=~p] [error=~p] [stack=~p]"

**Comment by Taure** [comment] 2020-04-28 15:51
Can I see this in Vs code or is it logged somewhere else?

**Comment by robertoaloi** [comment] 2020-04-28 16:34
https://erlang-ls.github.io/troubleshooting/

I’m interested in the server.log and the crash.log

**Comment by Taure** [comment] 2020-05-06 19:03
[crash.log](https://github.com/erlang-ls/erlang_ls/files/4588928/crash.log)

Ok, I only have a crash log for this. server.log was empty.

**Comment by robertoaloi** [comment] 2020-05-07 11:06
Hi @Taure, could you please share line 63/64 of the `nova_epm_builder` module? It's the line generating the two following diagnostics:

```
#{<<"diagnostics">> =>
                                                 [#{<<"message">> => <<"variable 'Dep' is unused">>,
                                                    <<"range">> =>
                                                        #{<<"end">> => #{<<"character">> => 0,<<"line">> => 64},
                                                          <<"start">> => #{<<"character">> => 0,<<"line">> => 63}},
                                                    <<"severity">> => 2,<<"source">> => <<"Compiler">>},
                                                  #{<<"message">> => <<"record fpm undefined">>,
                                                    <<"range">> =>
                                                        #{<<"end">> => #{<<"character">> => 0,<<"line">> => 64},
                                                          <<"start">> => #{<<"character">> => 0,<<"line">> => 63}},
                                                    <<"severity">> => 1,<<"source">> => <<"Compiler">>}]}
```

**Comment by robertoaloi** [comment] 2020-05-07 11:11
The culprit seems to be:

```
{ok, Tokens, _} = erl_scan:string(Line, 1, [return, text]),
```

But I'm trying to understand how could we end up in a situation where the compiler can return those warnings/errors but at the same time we are not able to parse the line.

**Comment by Taure** [comment] 2020-05-13 04:19
It was during a refactoring of code. Where it kind off made a new string with half of the module.

function(Abc") -> code.

.
. Everything between these two functions will be a string. For a time while refactoring the function header.
.

other_function("something")-> code.

But I will see if I can reproduce it in a file so we have something to look at.

**Comment by robertoaloi** [comment] 2020-12-06 12:49
@Taure Closing since not reproducible. Feel free to re-open if you manage to reproduce it.

**Closed by robertoaloi** 2020-12-06 12:49 UTC
Labels: bug, information required
