### ISSUE TITLE
Consider the auto-completion model used in elixir_ls

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#772] opened 2020-06-29 08:46 UTC
See the description [here](https://elixirforum.com/t/introducing-elixirls-the-elixir-language-server/5857/103)

**Comment by maxnordlund** [comment] 2020-09-12 09:50
Yes please. I always delete the arguments, because for some reason autocomplete doesn't trigger. But that might be a bug in VS Code, and I prefer to choose arity on the fly (if I want to add some options for example).

**Comment by robertoaloi** [comment] 2020-09-27 10:10
Hi @alanz since the description points to the whole changelog, may I ask you to formalize in this ticket the exact requirements?

**Comment by alanz** [comment] 2020-09-28 09:37
@robertoaloi I agree. IIRC one of my colleagues suggested that we look at this, without anything specific.

I am happy to close it if no-one else has anything concrete to put in here.

**Comment by maxnordlund** [comment] 2020-09-28 19:49
Instead of auto-completing with a snippet where the arguments are prefilled, leave empty places and let the user rely on auto-complete for the arguments. Also, always go for the highest arity since it easy to remove extra arguments, and at least I kinda forget which functions have an optional options argument.

Better

**Comment by robertoaloi** [comment] 2020-12-30 16:16
Hi @maxnordlund , during auto-completion, if multiple _arities_ are available for the same function name, all of them are proposed to the user. Arguments get expanded only after a specific arity is selected. I can see why the part about the function arguments can be annoying, I will check what I can do.

**Comment by robertoaloi** [comment] 2020-12-30 16:23
Actually, I double checked and the completions already use the _snippet_ format. This means that the arguments can be navigated via _TAB_ and the user can just type over, so no need to remove them. They are just placeholder.

**Comment by robertoaloi** [comment] 2020-12-30 16:38
I will close this for now as a _won't do_ from my side, but please feel free to contribute if you'd like to change how the auto-completion model works.

**Closed by robertoaloi** 2020-12-30 16:38 UTC
Labels: code completion

**Comment by maxnordlund** [comment] 2021-01-03 19:27
At least for me auto-completion doesn't trigger when overwriting snippet placeholders. Only if I exit the snippet mode (marked with an grey background for me) it starts working. That's why I would prefer to avoid using snippets if possible.

About suggesting multiple arities, the problem is that tabbing, in VS Code at least, selects the first alternative and switches to the snippet placeholders. Thus I can't actually select some other arity with tab, and must use arrow keys. Since lower arity goes first, I don't get the version with optional arguments.

By listing all arities one by one, it fills up/clutters the auto-complete list. I would prefer it to list each function name once, and indicate which arities are available, and prefer the highest arity when pressing tab.

If there were an option for disabling snippets, or perhaps not have placeholder _names_, just empty spaces `foo(, , ,)`, that would be swell.

I've tried to read through the source, but it's all a bit too much for me. Otherwise I would have made a PR 🙂
