### ISSUE TITLE
Poor formatting rules

### ISSUE THREAD

**Issue by illotum** [erlang-ls/erlang_ls#1408] opened 2022-11-18 22:09 UTC
Embedded erlfmt doesn't [respect code conventions](https://github.com/gomoripeti/erlfmt#in-clauses) and generally isn't consistent with standalone `erlfmt`

## To Reproduce
Input snippet:

```erlang
-module(some).

f2(A, B) -> {
     ok,
     yes}.

f(#{a := A, b := B, c := C}, Other) ->
        case f2(A, B) of
            undefined -> no;
            error -> no;
            {ok, _} -> yes
        end.
```

### Expected behavior
Formatting applied with escriptized WhatsApp/erlfmt, `erlfmt -w some.erl`:

```erlang
-module(some).

f2(A, B) ->
    {                                     %% respects standalone brace
        ok,
        yes
    }.

f(#{a := A, b := B, c := C}, Other) ->    %% wider line len
    case f2(A, B) of
        undefined -> no;                  %% respects inline cases
        error -> no;
        {ok, _} -> yes
    end.
```

### Actual behavior
Formatting applied (via NVIM's `vim.lsp.buf.format` callback):

```erlang
-module(some).

f2(A, B) ->
    {ok, yes}.

f(#{a := A,
    b := B,
    c := C},
  Other) ->
    case f2(A, B) of
        undefined ->
            no;
        error ->
            no;
        {ok, _} ->
            yes
    end.
```

## Context
 - `erlang_ls` version (tag/sha): 0.46.0
 - Editor used: NVIM v0.8.0
 - LSP client used: 
   - neovim/nvim-lspconfig@2b802ab
   - williamboman/nvim-lsp-installer@17e0bfa

**Comment by plux** [comment] 2024-09-26 12:14
Can't reproduce.
Are you sure `erlfmt` was configured as formatter?

Closing this, please re-open if I'm wrong :)

**Closed by plux** 2024-09-26 12:14 UTC
Labels: bug

**Comment by illotum** [comment] 2024-10-04 17:17
Are you reproducing it in v0.46? If it is fixed in v1, great!
