### ISSUE TITLE
rebar3 deps include_lib files ignored 

### ISSUE THREAD

**Issue by geib** [erlang-ls/erlang_ls#246] opened 2019-11-19 16:48 UTC
Just trying your new vscode package with the erlang_ls and found that include files that are part of dependency via rebar3 deps are ignored by erlang_ls. I can not find a way to point to these so that erlang_ls finds them. I tried adding erlang_ls.config with no luck. 

I did confirm that include_lib for include files in erlang, i.e. logger.hrl work fine.

So:

`-include_lib("kernel/include/logger.hrl").` **works**

but

`-include_lib("logit/include/logit.hrl").` **does not** when my rebar3 file include

```
{deps, [recon,
        **{logit, {git, "git@<gitlab host>:cse/erlang-utilities/logit.git", {tag, "1.0.0"}}},**
        {opencensus, "0.9.2"},
        {opencensus_zipkin, "0.2.0"},
        {ranch, "1.7.1"}]}.
```

**Comment by robertoaloi** [comment] 2019-11-19 17:41
Hi @geib and thanks for reporting. Could you share your `erlang_ls.config` file with us?

**Comment by geib** [comment] 2019-11-19 18:08
Sure. I created erlang_ls.config in the root of the project and tried all the following:

include_dirs: "_build/default/lib/logit/include"
then
include_dirs: "_build/default"
then
include_dirs: "_build/default/lib"
then
include_dirs: "_build/default/lib/logit"
and finally
include_dirs: "lib/logit/include"

BTW, I think during all this I was never able to get vscode to stop reporting that it could not find the file or directory I specified. Here is a screenshot.
![Screen Shot 2019-11-19 at 11 07 02 AM](https://user-images.githubusercontent.com/43514/69173352-d14f8380-0abc-11ea-9d56-a66ae8991085.png)

**Comment by geib** [comment] 2019-11-19 18:08
Just added to the BUG report.

Thanks,

Mark.

**Comment by robertoaloi** [comment] 2019-11-19 19:19
I think what you want is to set the `deps_dirs`:

```
deps_dirs:
  - "_build/default/lib/*"
```

Also notice how this is a **list** of directories.

Once #6 is implemented, you will be able to specify `project_type: rebar3` and all the required information will be automatically be extracted from your `rebar.config`.

**Comment by jfacorro** [comment] 2019-11-19 22:26
For a `rebar3` project you probably want what @robertoaloi showed plus the top level `include` dir if you have one:
```
deps_dirs:
  - "_build/default/lib/*"
  - "include"
```

**Comment by robertoaloi** [comment] 2019-11-20 08:15
@jfacorro I'm not sure that's needed. The "include" is part of `include_dirs`, which is independent from `deps_dirs`. We should really add an example, though.

**Comment by geib** [comment] 2019-11-20 16:12
So with this erlang_ls.config:

deps_dirs:
  - "_build/default/lib/*"


I see all macros in these include files:

-include_lib("logit/include/logit.hrl”). 	<— rebar3 dep
-include_lib("kernel/include/logger.hrl”).	<— erlang logger macros
-include("apps/ees/include/defines.hrl”).	<— local include directory for app

However, one thing I noticed/discovered was that on a fresh start of vscode the
erlang_ls application pinned two of the cores on my macbook for about 4 minutes.
If I wait for the process to quiet down then the behavior in vscode is much better.

Also, even with the erlang_ls.config file as above the erlang files that include
.hrl files from rebar3 deps always show and error for the include where it says
it can’t find the file. This make all the functions that use macros from that header
show up as undefined. The macros appear when I type “?”, but the file has error
indicators at each location in the file where the macro is used.

Mark.

**Comment by robertoaloi** [comment] 2019-11-21 09:02
@geib I think you need a `erlang_ls.config` file which contains both suggestions from me and @jfacorro. So:

```
deps_dirs:
  - "_build/default/lib/*"
include_dirs:
  - "_build/default/lib"
  - "include"
```

The high consumption of CPU/memory is due to the indexing. The latest version of the server is already including some improvements in that sense and we are still working on that.

**Comment by geib** [comment] 2019-11-21 16:01
Yes, agreed. I came to the same conclusion last night. With this erlang_ls.config
everything seems to work now, except the one case where I have an header file in the local
include directory for the app with macro defines. Those macros do not appear in the
list on typing “?”. After I open the header file, the macros defined in the file then
will appear the next time I type “?”. The same behavior when I move the header file into
the src directory.

**Comment by robertoaloi** [comment] 2019-11-23 15:44
@geib I could not reproduce that behaviour. Even without opening the `.hrl` file, auto-completion for macros seems to work correctly both for `include` and `include_lib` (as long as the header file is included in the current module). The only thing I can suggest would be for you to provide a minimal example (a repo including the module, the header file and the `erlang_ls.config` repo.

**Comment by geib** [comment] 2019-11-25 16:46
I have attached a small erlang release project that demonstrates the problem.
Prior to opening the defines.hrl file I do not see the macro “macro_from_include”
in the list. I do see the logger macros.

Mark.

**Comment by robertoaloi** [comment] 2019-11-26 08:21
@geib Did you intend to include a link somewhere?

**Comment by geib** [comment] 2019-11-26 15:59
No, I attached a tar-ball. I will create a github repo and upload.

**Comment by geib** [comment] 2019-12-03 21:43
Sorry, got distracted for a bit. Here is the repo link for the
project where I am not seeing the local macros which are defined
in a header file.

https://gitlab.com/els_testing/els_test_1.git

Thanks.

**Comment by geib** [comment] 2019-12-03 23:05
I just read #274 regarding the support for rebar3 projects. I assume my bug may be the result of this being a rebar3 "release", so src, include, etc. directories are not located in the root of the project.

**Comment by robertoaloi** [comment] 2019-12-04 09:21
@geib That seems to be the case. I will close this issue as superseded by #274. We will try to prioritize that piece of work, PRs are obviously welcome, too.

**Closed by robertoaloi** 2019-12-04 09:21 UTC
Labels: bug
