### ISSUE TITLE
Column ranges for compiler diagnostics are not correct

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#239] opened 2019-11-18 07:15 UTC
The compiler diagnostics report a hard-coded 1-character range in the lines where the diagnostic happens. Whilst this suffices in Emacs, diagnostics look weird in VSCode. Instead, the whole line should be added to the range and not just the first character.

**Comment by robertoaloi** [comment] 2019-11-18 13:14
This is also valid for dialyzer diagnostics, which are also off by one row.

**Comment by adam-becker** [comment] 2019-11-25 16:30
I don't know if extending to the whole line is the desired behavior, for an unused variable diagnostic I would expect just the variable name to be tagged.

On the topic of unused symbols, there must be _some_ way to implement this, since I've seen a few language server extensions show unused symbols as a darker color variation.

@robertoaloi Have you seen anything in the LSP that seems related?

**Comment by jfacorro** [comment] 2019-11-26 00:25
@adam-becker The root of the issue is not LSP itself, but the information the Erlang compiler provides regarding the position of the warnings and errors it returns. Only the line is provided by the compiler, no column (or range for that matter) is available.

**Comment by robertoaloi** [comment] 2019-11-26 07:53
@jfacorro is correct. In the messages returned by the compiler I could only see the line number. So, unless there is a way to get column information, we can't do much and either have a 1-char range (like today) or mark the whole line. For other checks (see for example #156 , we may be able to be more accurate on the column numbers.

**Comment by robertoaloi** [comment] 2019-11-26 08:18
@jfacorro is correct. In the messages returned by the compiler I could only see the line number. So, unless there is a way to get column information, we can't do much and either have a 1-char range (like today) or mark the whole line. For other checks (see for example #156 , we may be able to be more accurate on the column numbers.

**Comment by alanz** [comment] 2019-11-26 09:47
This is off-topic for this issue, but addressing @adam-becker, we could use the document highlights (just added).  A variable is highlighted with one of three values

```typescript
/**
 * A document highlight kind.
 */
export namespace DocumentHighlightKind {
	/**
	 * A textual occurrence.
	 */
	export const Text = 1;

	/**
	 * Read-access of a symbol, like reading a variable.
	 */
	export const Read = 2;

	/**
	 * Write-access of a symbol, like writing to a variable.
	 */
	export const Write = 3;
}
```

So in-use variables would be `Read` or `Write`, and others `Text`.

**Comment by michalmuskala** [comment] 2019-11-26 11:46
AFAIK if you parse the source code with column information, the compiler will report column positions. Or rather the start position of the error, but not the end one. To force this, the scanner needs to be given `{1, 1}` as initial location instead of just `1`. For example:
```erl
{ok, Tokens, _} = erl_scan:string("<<1:5/unit:8->>.", {1, 1}),
erl_parse:parse_exprs(Tokens).
% => {error,{{1,13},erl_parse,["syntax error before: ","'->'"]}} 
%% The error starts at line 1, column 13
```

Running the scanner with the additional `text` option also enables tracking the end location for individual tokens with `erl_anno:end_location(Anno)`, but this is entirely unused by the parser for reporting errors. 

I guess what would be possible is to mark the errors from the column given by the parser to the end of the line. It's less precise then particular location, but possibly more helpful than just highlighting the entire line.

**Comment by jfacorro** [comment] 2019-11-26 14:16
@michalmuskala Could it be possible that you are thinking of the parser, and not the compiler, which is the issue in this case?

**Comment by michalmuskala** [comment] 2019-11-26 14:35
If you feed forms annotated with column information to the compiler, it will report the column information back. 
```erl
{ok, T1, _} = erl_scan:string("-module(test).", {1, 1}).
{ok, T2, _} = erl_scan:string("foo() -> X.", {2, 1}).
{ok, F1} = erl_parse:parse_form(T1).
{ok, F2} = erl_parse:parse_form(T2).
compile:forms([F1, F2], [report, return, {source, "foo.erl"]).
% foo.erl:2:10: variable 'X' is unbound
% foo.erl:2:1 Warning: function foo/0 is unused
% => {error,[{"foo.erl",[{{2,10},erl_lint,{unbound_var,'X'}}]}],
%           [{"foo.erl",[{{2,1},erl_lint,{unused_function,{foo,0}}}]}]}
```
Printed messages

**Comment by jfacorro** [comment] 2019-11-26 14:53
@michalmuskala Nice! I didn't know that. I wonder why that is not just the default behaviour 😞.

**Comment by robertoaloi** [comment] 2019-11-26 15:39
@jfacorro My guess is that column numbers are a relatively recent addition, so the OTP team did not want to break the default behaviour for backward compatibility.

**Comment by jfacorro** [comment] 2019-11-26 15:42
I opened a PR where we report the whole line. Even though getting the column information is a step towards a nicer experience, we would still need to figure out where the range stops (e.g. for unusued variables). 

I think reporting the whole line provides a nicer result than reporting only a part of the line (i.e. starting from the column reported until the end of the line). 🤷‍♂

**Comment by michalmuskala** [comment] 2019-11-26 16:07
The main reason why I suggested starting from a middle of the line is that often parse errors specifically report something like `before ,`, which is not very helpful when there are multiple commas on the line. Having column information makes it easier. On the other hand, I agree that it might look weird in other cases.

**Comment by jfacorro** [comment] 2019-11-26 16:19
@michalmuskala That's a good point. We can definitely improve on this solution in a following PR to include the column information.

**Comment by robertoaloi** [comment] 2019-11-27 15:35
Removing from the current milestone, since the actual bug is fixed. Leaving it open, so we can implement support for column numbers.

**Comment by jfacorro** [comment] 2020-03-02 10:26
Including column information would require doing the parsing and compiling "manually", not through the `compile:file/2` function but by calling `erl_scan->erl_parse->compile` as in the snippet in one of the comments above. 

Do we want to pay the cost of maintaing that manual implementation for the benefit of having the column information?

**Comment by alanz** [comment] 2020-03-02 13:34
Perhaps this will get solved naturally as the compiler evolves in future.

**Comment by jfacorro** [comment] 2020-03-12 18:45
I think the current approach is good enough. I vote for closing this issue.

**Closed** 2020-03-13 14:54 UTC
Labels: bug, diagnostics, good first issue, vscode
